version: '3.8v'
services:
  PostgresSQL:
    image: postgres
    container_name: PostgresSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgress1
      - POSTGRES_PASSWORD=secretpostgres1
      - PGDATA=/data/postgres
    restart: unless-stopped

  PGAdmin:
    image: dpage/pgadmin4
    container_name: PG_admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-secretpgadmin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    
volumes:
  postgres:
  pgadmin:

    
